[project]
name = "skypro-frontend"
version = "0.1.0"
description = ""
authors = [
    {name = "Uriy-T",email = "briner_asterios@mail.ru"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django (>=6.1.1,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
